export const URLS = {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/register',
    VERIFY_EMAIL: '/auth/verify_email',
    CHECK_USERNAME: '/auth/check_if_username_exists',
    CHECK_EMAIL: '/auth/check_if_email_exists',
    RESEND_OTP: '/auth/resend_otp',
    UPDATE_COUNTRY_SATE: '/auth/update_country_state',
    PASSWORD_RESET_OTP: '/auth/password_reset_otp',
    RESET_PASSWORD: '/auth/reset_password',
    INCREMENT_POST_VIEWS: '/increment_post_views',
    GET_SINGLE_POST: '/fetch_single_post_by_id',
    GET_TRENDING_POSTS: '/fetch_trending_posts',
    REACT_TO_POST: '/react_to_post',
    POST_COMMENT: '/create_comment',
    UPVOTE_POST: '/upvote_post',
    DOWN_VOTE_POST: '/downvote_post',
    REPOST: '/repost',
    GET_POSTS: '/fetch_posts',
    TOP_STORIES: '/fetch_top_stories_posts',
    MOST_UPVOTES: '/fetch_posts_with_highest_upvotes',
    MOST_COMMENTS: '/fetch_posts_with_highest_comments',
    MOST_REACTIONS: '/fetch_posts_with_highest_reactions',
    GET_POST: '/fetch_posts',
    CHATTED_USER: '/fetch_chatted_users',
    GET_CHAT_MESSAGES: '/fetch_messages',
    POST_CHAT_MESSAGE: '/send_message',
}