export enum COMMUNITY_SETTING_TYPE {
    DEFAULT = 0,
    EDIT,
    TYPE,
    REQUEST,
    MEMBERS,
    POSTS,
    SUSPENDED_MEMBERS,
    BLOCKED_MEMBERS,
    INVITE,
    MODERATORS,
    RULES,
    UPDATE_RULE,
    ADD_RULE,
    REMOVAL_RREASON,
    ADD_REMOVAL_REASON,
    UPDATE_REMOVAL_REASON,
    CONTENT_CONTROL
}